URECA-Cookie/Cookie-FE

- cookie/package-lock.json
- cookie/src/components/searchpage/MovieListSection.jsx
- cookie/src/components/searchpage/SearchBar.jsx
- cookie/src/components/searchpage/SearchResults.jsx
- cookie/src/components/searchpage/TopButton.jsx
- cookie/src/pages/search.jsx
- cookie/yarn.lock
> #19 Refactor: 영화 검색 페이지 컴포넌트화
> 영화 검색 페이지 구조 컴포넌트화, 영화제목, 감독명, 배우명 별 검색결과 구분
> Refactor: 영화 검색 페이지 컴포넌트화

- cookie/src/pages/LikedMovies.jsx
- cookie/src/pages/ManageProfile.jsx
- cookie/src/pages/MovieDetail.jsx
- cookie/src/pages/main.jsx
- cookie/src/pages/mypage.jsx
> #26 
> import문 제거를 하지않아서 오류가 생김
> Fix: import 오류 해결

- cookie/src/pages/LikedMovies.jsx
- cookie/src/routes/AppScreen.jsx
> Design: 카드형태 무너진것 수정

- cookie/src/components/mypage/ReviewList.jsx
> #30 
> 티켓 반응형으로 만들었습니다.
재수정본 
(풀 스크린)
(줄였을 때)
> Design: 리뷰티켓 반응형 완료

- cookie/src/components/mypage/BadgeList.jsx
- cookie/src/components/mypage/GenreChart.jsx
- cookie/src/components/mypage/ProfileImage.jsx
- cookie/src/components/mypage/ReviewList.jsx
- cookie/src/pages/MatchupPage.jsx
- cookie/src/pages/mypage.jsx
- cookie/src/routes/RouteDef.jsx
> Feat: MYPAGE API MAPPING

- cookie/src/components/mypage/NicknameInput.jsx
- cookie/src/components/mypage/SetProfileImage.jsx
- cookie/src/pages/ManageProfile.jsx
> Feat: 프로필 관리 매핑

- cookie/src/api/auth/ReTokenPage.jsx
- cookie/src/api/auth/axiosInstance.js
- cookie/src/pages/SignUpGenre.jsx
- cookie/src/pages/SignUpProfile.jsx
- cookie/src/routes/RouteDef.jsx
> ex) #46 
> 회원가입페이지 닉네임 중복검사 api연동 확인 
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> feat: 회원가입페이지 닉네임 중복확인 api연동 완료

- cookie/src/routes/AppScreen.jsx
> Feat: 로고 클릭시 home으로 설정

- cookie/src/components/signUp/Modal.jsx
- cookie/src/config/OAuthConfig.js
- cookie/src/pages/SignUpGenre.jsx
> fix: Oauth url 수정

- cookie/src/pages/mypage.jsx
> #71
> 테스트를 위한 서버주소 -> 배포주소 변경
> update: 마이페이지 테스트를 위한 배포주소로 변경

- cookie/src/components/matchup/ChatMessages.jsx
- cookie/src/components/matchup/ChatUI.jsx
- cookie/src/pages/MatchupPage.jsx
> Refactor: 채팅 UI 반응형 적용:

- cookie/src/components/main/MatchUp.jsx
- cookie/src/pages/SignUpGenre.jsx
- cookie/src/pages/main.jsx
> update: 매치업 더미데이터 수정

- cookie/src/api/auth/axiosInstance.js
> #100 
> instance 요청시 헤더 중복 수정
> 확인해주세요~!
> fix: axiosInstance 오류 수정

- cookie/src/api/auth/ReTokenPage.jsx
- cookie/src/components/signUp/Modal.jsx
- cookie/src/pages/Login.jsx
- cookie/src/pages/SignUpGenre.jsx
- cookie/src/pages/SignUpProfile.jsx
- cookie/src/pages/main.jsx
- cookie/src/stores/useUserStore.js
> #104 
> 로그인 및 회원가입페이지 메인컬러 변경
> 로그인 및 회원가입 유저정보 상태 관리 추가
(변경 전)
(변경 후)
확인해주세요!
> 📎 회원가입 또는 로그인 시 메인 하단에 임시로 정보 확인 가능! (현재 메인에 적용해놓음)
> 필요한 페이지에 유저스토어 가져오기
> const userInfo = useUserStore((state) => state.getUserInfo()); 
> {userInfo.nickname} (JSX부분) 
> 📎로그인 인증 메서드 추가
> 로그인이 가능해야 접근가능한 부분은 구조분해할당으로 isLogined 불러와서
> const { isLogined } = useAuthStore();
> 해당 핸들러에 successPath 넣어주면 됩니다!
> ex) onClick={() => isLogined("/searchmov")}
> *현재 메인 리뷰쓰기버튼에 적용되어있음
> update: 회원가입 및 로그인 유저 상태관리 추가

- cookie/src/pages/mypage.jsx
>  #113 
> 회원가입 탈퇴기능을 만들어보았어요! 
> 테스트부탁드립니다 !여러분들 환경에서도 ~
> Feat:#113 회원탈퇴기능 추가

- cookie/src/components/main/CookieMovies.jsx
- cookie/src/components/main/GenreMovie.jsx
- cookie/src/components/main/MatchUp.jsx
- cookie/src/components/main/RankMovie.jsx
- cookie/src/components/main/SpecialMovie.jsx
- cookie/src/pages/main.jsx
- cookie/src/stores/useUserStore.js
- cookie/src/styles/global.js
> #111 
> 관리자추천 및 매치업 영화데이터 api연동
> 글로벌 스타일 변경 색 적용
> 데이터 화면에 보여지는것까지 확인했고 이후 수정사항은 버전2에 반영예정 입니다!
> Feat 메인페이지 영화 데이터 api 연동

- cookie/src/components/searchpage/ReviewContentSection.jsx
- cookie/src/pages/MovieReviewFeed.jsx
- cookie/src/pages/ReviewDetail.jsx
- cookie/src/pages/search.jsx
> #125
> 리뷰 좋아요 적용
> 특정 영화 리뷰 피드 페이지
>
> UI
> Feat/#125 리뷰 좋아요 적용 & 특정 영화 리뷰 피드

- cookie/src/components/movieDetailPage/DetailsSection.jsx
- cookie/src/components/searchpage/SearchResultsForReview.jsx
- cookie/src/pages/MovieReviewFeed.jsx
- cookie/src/pages/MovieReviewForm.jsx
- cookie/src/pages/ReviewForm.jsx
- cookie/src/pages/SearchForReview.jsx
> #130
> 메인페이지의 리뷰 작성하기 버튼 -> 리뷰할 영화 검색 -> 리뷰 작성
> 영화 검색 페이지 -> 영화 상세 페이지 -> 리뷰 작성하기
> 위 두가지 flow로 작성이 가능합니다.
> flow 직접 체험해보세요:)
> Feat/#130 review api 에러해결

- cookie/src/pages/ReviewDetail.jsx
> #138
> 리뷰 창에서 댓글 수정시 모달창이 뜨게 해봤어요!
> UI 맘에 안들면 말해주세요~
> feat: 리뷰 댓글 수정시 모달창 구현

- cookie/src/pages/ReviewDetail.jsx
> #138
> 댓글이 두번 입력되는 버그를 수정했습니다
> 특별한 리뷰는 필요없습니다!
> hotfix: 댓글 두번 입력되는 버그 수정

- cookie/src/components/main/AdminRecommend.jsx
- cookie/src/components/main/GenreMovie.jsx
> #136
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> Refactor: #136 메인페이지 영화 상세보기 경로 수정

- cookie/src/components/searchpage/ReviewContentSection.jsx
- cookie/src/pages/ReviewDetail.jsx
- cookie/src/pages/mypage.jsx
> #141 
> 내가 쓴 리뷰 수정 삭제
> 브랜치떙겨서 확인좀용
> Feat:#141 내가 쓴 리뷰 수정 삭제

- cookie/src/api/auth/ReTokenPage.jsx
- cookie/src/components/main/AdminRecommend.jsx
- cookie/src/components/main/CookieMovies.jsx
- cookie/src/components/main/GenreMovie.jsx
- cookie/src/components/main/MatchUp.jsx
- cookie/src/stores/useUserStore.js
> #163
> 장르별 카테고리 페이지네이션 적용
> 쿠키리즘 유저정보 로컬스토리지에 저장되는 부분 닉네임만 저장되도록 변경
> 매치업, 관리자 추천 스켈레톤 효과적용
> Refactor : #163 메인페이지 리펙토링 

- cookie/src/components/movieDetailPage/CastDetail.jsx
- cookie/src/components/movieDetailPage/CastSection.jsx
- cookie/src/pages/ReviewDetail.jsx
> #168 
> 프로필 이미지 없는 배우/감독의 경우 default image setting
> 리뷰 상세보기에서 비로그인 유저 리뷰 작성 시도시 예외처리
> 리뷰 상세보기에서 비로그인 유저 좋아요 시도시 예외처리
> UI
> Fix: 3차 피드백

- cookie/src/components/movieDetailPage/ReviewSection.jsx
- cookie/src/components/searchpage/ReviewContentSection.jsx
- cookie/src/pages/ReviewDetail.jsx
> #168
> 리뷰 상세 페이지에서 포스터 클릭시 영화 상세보기
> 영화 상세 페이지에서 리뷰 클릭시 리뷰 상세보기
> 로그인 필요한 곳 모달 통일
> UI
> Fix/#168 3차 피드백

- cookie/src/components/main/AdminRecommend.jsx
- cookie/src/components/main/CookieMovies.jsx
- cookie/src/components/main/GenreMovie.jsx
- cookie/src/components/main/SpecialMovie.jsx
- cookie/src/pages/CategoryMovieFeed.jsx
- cookie/src/routes/AppScreen.jsx
> #170
> 메인페이지 스크롤버튼 추가 및 로그인 모달연결
>
> Refactor #170 메인 스크롤버튼 추가 및 로그인 모달 연결

- cookie/src/components/movieDetailPage/DetailsSection.jsx
- cookie/src/pages/ReviewDetail.jsx
> #168
> 리뷰 상세 페이지에서 비로그인 유저 댓글 작성 시도시 처리
> 영화 상세 페이지에서 비로그인 유저 좋아요 시도시 처리
> 영화 상세 페이지에서 비로그인 유저 리뷰 작성 시도시 처리
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요  
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Feat/#168 3차feedback

- cookie/src/pages/mypage.jsx
- cookie/src/stores/useAuthStore.js
> #178 
> 로그인 상태를 주스탠트 펄시스턴트로 관리하여, 새로고침이 되더라도 로그인 상태를 안정적으로 관리 할수 
있도록 하였습니다.
> 로컬 스토리지 확인하면될거같아요
> Feat:#178 로그인상태 주스탠드 펄시스턴트 적용

- cookie/src/components/matchup/TitleSection.jsx
- cookie/src/components/mypage/PushNotificationToggle.jsx
- cookie/src/pages/LikedMovies.jsx
- cookie/src/pages/Login.jsx
- cookie/src/pages/PointHistoryPage.jsx
- cookie/src/pages/mypage.jsx
- cookie/src/stores/useAuthStore.js
> #189 
> 조그마한 일부버그들 수정했어요
> ㅎㅎ..
> Fix: 일부 작은 버그 수정

- cookie/src/components/mypage/PushNotificationToggle.jsx
- cookie/src/pages/mypage.jsx
> #191 
> 푸쉬 알림 on/off를 할 수 있다.
> 잘 봐주세용 ~~
> Feat:#191 푸쉬알림 on/off 기능 완성

- cookie/src/components/main/MatchUpSection.jsx
- cookie/src/components/matchup/Modal.jsx
- cookie/src/components/movieDetailPage/CastDetail.jsx
- cookie/src/components/searchpage/ReviewContentSection.jsx
- cookie/src/components/searchpage/ReviewDetailHeader.jsx
- cookie/src/components/searchpage/ReviewTextSection.jsx
- cookie/src/components/searchpage/SearchResults.jsx
- cookie/src/pages/LikedMovies.jsx
- cookie/src/pages/PointHistoryPage.jsx
- cookie/src/pages/ReviewDetail.jsx
> #196 
> 전체적으로 리팩했어요 (눈에 거슬리는것들)
> 리뷰달아주떼욤~
> Refactor: 전체적으로 리팩했어요

- cookie/index.html
> #199 
> 구글 애널리틱스 테스트
> 배포한번만요 금정님 🤍🤍
> Feat/#199 구글 애널리틱스 설정

- cookie/src/components/searchpage/SearchResultsForReview.jsx
- cookie/src/pages/MovieDetail.jsx
- cookie/src/pages/SearchForReview.jsx
> #201
> 영화 상세 페이지 스틸컷 없는 영화 예외처리
> 영화 상세 페이지 동영상 없는 영화 예외처리
> 영화 상세 페이지 이미지 없는 영화 예외처리
> 메인 페이지에서 리뷰 등록하기 클릭 시 리뷰 등록할 영화 검색 UI
> X
> Fix/#201 4차 feedback

- cookie/src/pages/ReviewForm.jsx
> feat: 리뷰 작성시 중복 등록 방지

- cookie/src/api/auth/ReTokenPage.jsx
- cookie/src/components/matchup/ChatInput.jsx
- cookie/src/components/matchup/ChatMessages.jsx
- cookie/src/components/matchup/ChatUI.jsx
- cookie/src/stores/useUserStore.js
> #208 
> 내 메세지인데도 상대 메세지인 것처럼 인식하는 버그 수정했어요
> 테스트해봅시다 배포올려서
> Fix: #208 채팅 버그 수정

- cookie/public/assets/images/movie/pencil.svg
- cookie/src/components/movieDetailPage/CastSection.jsx
- cookie/src/components/movieDetailPage/DetailsSection.jsx
- cookie/src/components/movieDetailPage/ReviewSection.jsx
- cookie/src/components/movieDetailPage/VideoSection.jsx
- cookie/src/pages/MovieDetail.jsx
> #216
> 영화 상세보기 페이지 UI 리팩토링
> 땡겨서 확인 부탁드립니다 영화 상세 페이지
> Refactor: #216 영화 상세보기 페이지 UI 리팩토링

- cookie/src/components/layout/Header.jsx
- cookie/src/components/searchpage/ReviewHeader.jsx
- cookie/src/pages/ReviewForm.jsx
> #221
> 리뷰 작성 페이지 UI 수정
> 간단하게 수정했습니다.
> Refactor: #221 리뷰 작성 페이지 UI 수정

- cookie/src/api/auth/ReTokenPage.jsx
- cookie/src/components/common/LoginModal.jsx
- cookie/src/components/layout/Footer.jsx
- cookie/src/components/main/MatchUpSection.jsx
- cookie/src/components/matchup/Modal.jsx
- cookie/src/components/matchup/Poster.jsx
- cookie/src/components/matchup/PosterList.jsx
- cookie/src/components/matchup/Timer.jsx
- cookie/src/components/matchup/TitleSection.jsx
- cookie/src/pages/MatchupPage.jsx
- cookie/src/pages/SignUpGenre.jsx
- cookie/src/stores/useUserStore.js
> #228 
> 매치업 리팩토링했어요 ~~
비밀 ~ ㅋ
> 히스토리 위주로 했어영
> Refactor:#228 매치업 리팩토링

- cookie/src/components/movieDetailPage/GallerySection.jsx
- cookie/src/components/searchpage/SearchResults.jsx
- cookie/src/pages/MovieDetail.jsx
> Feat/#234 페이지 반응형

- cookie/src/components/movieDetailPage/HeaderSection.jsx
> #234
> 영화 상세페이지 스틸컷 모바일뷰 적응형
> X
> feat: 영화 상세페이지 스틸컷 적응형

- cookie/src/pages/search.jsx
>  #234 
> 검색 모바일 반응형 피드백 반영
> X
> feat: 검색 모바일 반응형 피드백 반영

- cookie/src/pages/ReviewFeed.jsx
> #234
> 리뷰 피드 페이지 모바일 반응형
> X
> feat: 리뷰 피드 페이지 모바일 반응형

- cookie/src/pages/MovieReviewFeed.jsx
> feat: 특정영화리뷰피드 반응형 초안

- cookie/src/components/main/AdminRecommend.jsx
- cookie/src/components/main/CookieMovies.jsx
- cookie/src/components/main/GenreMovie.jsx
- cookie/src/components/main/MatchUpSection.jsx
- cookie/src/components/main/SpecialMovie.jsx
- cookie/src/components/searchpage/TopButton.jsx
- cookie/src/pages/main.jsx
> #249 
> 메인페이지 포스터 및 리뷰쓰기버튼 반응형 수정했습니다.
> Refactor: #249 메인 이미지 반응형 적용

- cookie/src/pages/MovieReviewFeed.jsx
> #262
> 특정 영화 리뷰 피드페이지 인기순 정렬
> 와일드 로봇으로 보시면 보기 편할거에요:)
> 특정 영화 리뷰 피드페이지 인기순 정렬 추가
